#########################################################
# SNAKEFILE FOR LINEAGE PAN-GENOME ASSEMBLIES CASE STEP #
#########################################################

# Notes:
# # This is a simplified case step that only generates a coverage matrix and does not attempt to find variant positions.

# Reminders:
# # Put your own email address in cluster.slurm.json so that you get emails about failures. No one else wants your slurm emails.



''' SETUP '''

# csv file with information on 

## USER defined variables (in theory do not need to be touched)
spls = "samples_case.csv" # TAG_BYCLADE

import sys
SCRIPTS_DIRECTORY = "/scratch/mit_lieberman/projects/aro_cacnes_biogeo/lab_scripts"
sys.path.insert(0, SCRIPTS_DIRECTORY)

import subprocess

from read_samplesCSV import read_samples_caseCSV

maxFQ = -30 # purity threshold (from mapping quality) for including position

DIR_ASSEMBLY_MAPPING = "/scratch/mit_lieberman/projects/aro_cacnes_biogeo/5_lineage_assembly_mapping/"



''' PRE-SNAKEMAKE '''

## define couple of lists from samples_case.csv
## FORMAT: Path,Sample,ReferenceGenome,Outgroup
# NOTE: case analysis expects:
#	- only a single ref genome used for all samples
#	- unique sample IDs
#	- Col1==Paths, points to the snakemake directory used for mapping, not raw data! > only single entries accepted!
[PATH_ls, SAMPLE_ls, REF_Genome_ls, OUTGROUP_ls] = read_samples_caseCSV(spls)


''' SNAKEMAKE '''
rule all:
    input:
        # # Data links only # #
        expand("data/diversity/{sampleID}_clade_{references}_outgroup{outgroup}.diversity.mat",zip,sampleID=SAMPLE_ls, references=REF_Genome_ls, outgroup=OUTGROUP_ls),
        # # Everything # #
        "2-candidate_mutation_table/coverage_matrix.mat",
        # # Including cleanup step # #
        "logs/cleanUp_done.txt",


rule build_data_links:
	output:
		div_mat_links = expand("data/diversity/{sampleID}_clade_{references}_outgroup{outgroup}.diversity.mat",zip,sampleID=SAMPLE_ls, references=REF_Genome_ls, outgroup=OUTGROUP_ls),
	run:
		import subprocess
		subprocess.run( "rm -fr data/ " ,shell=True) # clean it up prior run
		subprocess.run( "mkdir -p data/vcf/ data/qual/ data/diversity/ " ,shell=True)
		for i in range(len(SAMPLE_ls)):
			subprocess.run( "ln -fs -T " + PATH_ls[i] + "/11-diversity/" + SAMPLE_ls[i] + "_clade_" + REF_Genome_ls[i] + "*diversity.mat data/diversity/" + SAMPLE_ls[i] + "_clade_" + REF_Genome_ls[i] + "_outgroup" + OUTGROUP_ls[i] + ".diversity.mat" ,shell=True)


# build input for candidate_mutation_table
rule string_diversity_mat:
    input:
    	diversity_mat = expand("data/diversity/{sampleID}_clade_{references}_outgroup{outgroup}.diversity.mat",zip,sampleID=SAMPLE_ls, references=REF_Genome_ls, outgroup=OUTGROUP_ls),
    output:
    	string_diversity_mat = "1-temp_pos/string_diversity_mat.txt",
    run:
    	with open( output.string_diversity_mat ,"w") as f: 
    		print(*input.diversity_mat, sep=" ", file=f)


# build input for candidate_mutation_table
rule string_sampleID_names:
    params:
    	sampleID_names = expand( "{sampleID}" , sampleID=SAMPLE_ls ),
    output:
    	string_sampleID_names = "1-temp_pos/string_sampleID_names.txt",
    shell:
    	"""
    	for i in {params.sampleID_names}; do
    	 echo $i
    	done |tr '\n' ' ' |sed "s/ $//" > {output.string_sampleID_names};
        """


# generate coverage matrix (matlab version)
rule coverage_matrix_mat:
    input: 
        string_sampleID_names = "1-temp_pos/string_sampleID_names.txt",
        string_diversity_mat = "1-temp_pos/string_diversity_mat.txt",
    output:
        coverage_mat = "2-candidate_mutation_table/coverage_matrix.mat",
    log:
        'logs/coverage_matrix.log',
    shell:
        """
        module add mit/matlab/2015b; 
        matlab -r "path('{SCRIPTS_DIRECTORY}',path); get_all_coverage_snakemake( '{input.string_sampleID_names}', '{input.string_diversity_mat}', '{output.coverage_mat}' )" > {log} 2>&1
        """


rule cleanUp:
    input:
        coverage_mat = rules.coverage_matrix_mat.output.coverage_mat, # "2-candidate_mutation_table/candidate_mutation_table.mat",
    params:
        temp_folder = "1-temp_pos"
    output:
        "logs/cleanUp_done.txt"
    shell:
        " rm -rf {params.temp_folder} ; touch {output} "

